import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.110.2/+esm'
const C={url:'https://goedzzhhvvnfczgnkqlv.supabase.co',key:'sb_publishable_6whjqbImNMa7BR9i-96M-w_dFIOFeMN',bucket:'restoration-media',chunk:16*1024*1024,buffer:12}
const db=createClient(C.url,C.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})
const S={user:null,profile:null,file:null,jobs:[],workers:[],view:'home',paused:false,admin:false}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const bytes=n=>{n=Number(n||0);if(!n)return'0 B';let u=['B','KB','MB','GB','TB'],i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
const date=x=>x?new Date(x).toLocaleString('zh-TW'):'—',safe=n=>n.replace(/[^A-Za-z0-9._-]+/g,'_').slice(-180)||'media.bin',ext=n=>(n.toLowerCase().match(/\.[a-z0-9]{1,10}$/)||[''])[0]
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),online=w=>w&&Date.now()-new Date(w.last_seen_at).getTime()<120000
async function hash(v){let b=typeof v==='string'?new TextEncoder().encode(v):await v.arrayBuffer();return[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function token(){let b=crypto.getRandomValues(new Uint8Array(32));return'rst_'+btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function toast(m,bad=false){let t=$('toast');t.textContent=m;t.className='toast '+(bad?'bad':'');clearTimeout(toast.t);toast.t=setTimeout(()=>t.className='toast hidden',4200)}
function nav(v){S.view=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`v-${v}`));document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('on',x.dataset.v===v));if(v==='jobs')loadJobs();if(v==='workers')loadWorkers();if(v==='account')profileUI();if(v==='admin'&&S.admin)loadAdmin();scrollTo({top:0,behavior:'smooth'})}
function shell(){document.body.innerHTML=`<div id="toast" class="toast hidden"></div><header><b class="brand"><i>R</i> Restoration Studio</b><nav><button data-v="home" class="on">首頁</button><button data-v="workspace">工作台</button><button data-v="jobs">工作</button><button data-v="workers">節點</button><button data-v="account">個人</button><button id="adminNav" data-v="admin" class="hidden">管理</button></nav><div><span id="who"></span><button id="authBtn" class="outline">登入</button><button id="logout" class="outline hidden">登出</button></div></header><main>
<section id="v-home" class="view active"><div class="hero"><div><small>DURABLE MEDIA RESTORATION</small><h1>長影片修復，<br>斷線也不用重來。</h1><p>授權圖片與長影片的可續傳、可恢復、可驗證修復。兩小時影片採16 MB傳輸分段與5分鐘處理檢查點。</p><button data-v="workspace">開始建立工作</button><button data-v="workers" class="outline">安裝Worker</button><div class="chips"><span>私有雲端分段</span><span>SHA-256驗證</span><span>失敗重試</span><span>高清輸出</span></div></div><div class="card"><h2>服務狀態</h2><div class="row"><span>網站與HTTPS</span><b class="ok">正常</b></div><div class="row"><span>帳號與控制平面</span><b id="dbState">檢查中</b></div><div class="row"><span>個人Worker</span><b id="wkState">未連線</b></div><p>來源分段被Worker驗證、落盤後便從雲端刪除，避免整支影片長時間占用免費儲存。</p></div></div><div class="notice"><b>可信度界線：</b>改善去壓縮、降噪、去交錯、銳化與解析度，不保證找回被完整刪除、塗黑或刻意馬賽克遮蔽的真實像素。</div></section>
<section id="v-workspace" class="view"><div class="head"><div><small>WORKSPACE</small><h2>建立修復工作</h2></div></div><div class="grid"><div class="card"><label class="drop"><input id="file" type="file" accept="image/*,video/*" hidden><b id="fileName">選擇圖片或影片</b><span id="fileInfo">MP4、MOV、MKV、WebM與常見圖片</span></label><div class="two"><label>修復強度<select id="preset"><option value="light">保守</option><option value="balanced" selected>平衡</option><option value="strong">強力</option></select></label><label>輸出高度<select id="height"><option>720</option><option selected>1080</option><option>1440</option><option>2160</option></select></label></div><div class="checks"><label><input id="deblock" type="checkbox" checked>去方塊</label><label><input id="denoise" type="checkbox" checked>降噪</label><label><input id="deband" type="checkbox" checked>去色帶</label><label><input id="deinterlace" type="checkbox" checked>去交錯</label><label><input id="sharpen" type="checkbox" checked>銳化</label><label><input id="report" type="checkbox" checked>可信度報告</label></div><label class="consent"><input id="consent" type="checkbox">我確認素材為本人所有或已取得授權，不用於破解他人隱私遮蔽。</label><button id="upload" disabled>開始可續傳上傳</button><button id="pause" class="outline hidden">暫停</button><div id="progress" class="progress hidden"><div><i id="bar"></i></div><span id="stage">準備中</span><b id="pct">0%</b></div></div><div class="card"><h2>上傳前檢查</h2><div class="row"><span>登入</span><b id="pfAuth">否</b></div><div class="row"><span>Worker</span><b id="pfWorker">未連線</b></div><div class="row"><span>分段</span><b>16 MB</b></div><div class="row"><span>最大超前緩衝</span><b>192 MB</b></div><p>大型檔案在Worker離線或緩衝達上限時會安全等待，不會默默失敗。</p></div></div></section>
<section id="v-jobs" class="view"><div class="head"><h2>我的工作</h2><button id="refreshJobs" class="outline">更新</button></div><div id="jobs" class="list"></div></section>
<section id="v-workers" class="view"><div class="head"><h2>個人處理節點</h2></div><div class="grid"><div class="card"><h3>下載與安裝</h3><p>Windows、macOS、Linux與Docker均可使用。</p><a class="button" href="https://github.com/PAQ6809/test-wsl/archive/refs/heads/main.zip">下載完整原始碼</a><a class="button outline" href="https://raw.githubusercontent.com/PAQ6809/test-wsl/main/worker/install-worker.ps1">Windows一鍵安裝</a></div><div class="card"><h3>建立配對金鑰</h3><label>節點名稱<input id="workerName" value="Personal Worker"></label><button id="newToken">建立一次性金鑰</button><pre id="tokenBox" class="hidden"></pre><button id="downloadEnv" class="outline hidden">下載.env</button></div></div><h3>已連線節點</h3><div id="workers" class="list"></div></section>
<section id="v-account" class="view"><div class="head"><h2>個人頁面</h2></div><div id="guest" class="empty">請先登入</div><div id="account" class="grid hidden"><form id="profileForm" class="card"><h3>基本資料</h3><label>顯示名稱<input id="displayName"></label><label>電子郵件<input id="email" disabled></label><label>語言<select id="locale"><option value="zh-TW">繁體中文</option><option value="en">English</option></select></label><button>儲存</button></form><div class="card"><h3>資料與安全</h3><div class="row"><span>方案</span><b id="plan">Free</b></div><div class="row"><span>邏輯額度</span><b id="quota">—</b></div><label>新密碼<input id="password" type="password" minlength="10"></label><button id="changePassword" class="outline">更新密碼</button><button id="deleteJobs" class="danger">刪除全部工作</button></div></div></section>
<section id="v-admin" class="view"><div class="head"><h2>管理與監控</h2><button id="refreshAdmin" class="outline">更新</button></div><div id="metrics" class="metrics"></div><div class="grid"><div class="card"><h3>最近工作</h3><div id="adminJobs"></div></div><div class="card"><h3>Worker</h3><div id="adminWorkers"></div></div></div></section>
</main><footer>Restoration Studio Cloud v1.0 · 僅處理授權素材</footer><dialog id="auth"><div class="tabs"><button id="loginTab">登入</button><button id="signupTab" class="outline">註冊</button></div><form id="loginForm"><label>電子郵件<input id="loginEmail" type="email" required></label><label>密碼<input id="loginPass" type="password" required></label><button>登入</button></form><form id="signupForm" class="hidden"><label>顯示名稱<input id="signupName" required></label><label>電子郵件<input id="signupEmail" type="email" required></label><label>密碼<input id="signupPass" type="password" minlength="10" required></label><button>建立帳號</button></form><p id="authError" class="badText"></p><button id="closeAuth" class="outline">關閉</button></dialog>`}

export {C,db,S,$,esc,bytes,date,safe,ext,sleep,online,hash,token,toast,nav,shell}
